# Generated by Django 3.1.2 on 2020-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('rss_url', models.CharField(max_length=255)),
                ('joplin_folder', models.CharField(max_length=80, null=True)),
                ('reddit', models.CharField(max_length=80, null=True)),
                ('mastodon', models.BooleanField(default=False)),
                ('mail', models.BooleanField(default=False)),
                ('localstorage', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_triggered', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Trigger',
            },
        ),
    ]
